spring.application.name=volvo
server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/juegos_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.main.allow-bean-definition-overriding=true

services.genero.url=http://localhost:8081/api/v1/generos
services.plataforma.url=http://localhost:8082/api/v1/plataformas
services.estudio.url=http://localhost:8084/api/v1/estudios

#config-swagger

#ruta
springdoc.swagger-ui.path=/swagger-ui.html