spring.application.name=volvo
server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/juegos_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#services.genero.url=http://localhost:8081
#services.platforma.url=http://localhost:8082
#services.estudio.url=http://localhost:8084